SOLR_URL = "http://localhost:8983/solr/humboldt"
SOLR_SELECT_URL = SOLR_URL + "/select?wt=json"
SOLR_QUERY_URL = SOLR_URL + "/query"

MIN_AGE = 16
MAX_AGE = 81
P_LEVELS = [0.01, 0.05, 0.1]
ROLLING_MEAN_FRAME = 2

# list of language code, country code, language name, and country name
AVAILABLE_OPTIONS = [('da', 'dk', 'Danish', 'Denmark'),
                     ('en', 'uk', 'English', 'UK')]  # , ('fr', 'fr', 'French', 'France')]

# map info: latitude, longitude, zoom level
MAP_VIEWS = {
    'uk': ([54.5, -4], 5),
    'dk': ([56, 10.5], 6),
}

NOT_AVAIL = "NA"

NUTS_NAMES = {"DEG0H": "Sonneberg", "AT224": "Oststeiermark", "PL214": "Krakowski", "PL613": "Bydgosko-Torunski",
              "ITH56": "Ferrara", "TRC11": "Gaziantep", "DE27E": "Oberallgäu", "DE222": "Passau, Kreisfreie Stadt",
              "UKD61": "Warrington", "DE21N": "Weilheim-Schongau", "PT112": "Cávado", "FI1D3": "Pohjois-Karjala",
              "CH066": "Zug", "NL337": "Agglomeratie Leiden en Bollenstreek", "CH053": "Appenzell Ausserrhoden",
              "EL431": "Irakleio", "DE265": "Bad Kissingen", "DEA54": "Hamm, Kreisfreie Stadt", "PL417": "Leszczynski",
              "FR213": "Marne", "DEA1E": "Viersen", "CH064": "Obwalden", "DE949": "Emsland", "FR261": "Côte-d'Or",
              "AT321": "Lungau", "DEF03": "Lübeck, Kreisfreie Stadt", "NL33A": "Zuidoost-Zuid-Holland",
              "ES618": "Sevilla", "UKH23": "Hertfordshire", "CH070": "Ticino", "DEA57": "Hochsauerlandkreis",
              "TR412": "Eskisehir", "ITI33": "Macerata", "PT300": "Região Autónoma da Madeira (PT)",
              "NL342": "Overig Zeeland", "UKH24": "Bedford", "TR321": "Aydin", "DEA12": "Duisburg, Kreisfreie Stadt",
              "DE24D": "Wunsiedel im Fichtelgebirge", "DE946": "Ammerland", "CH012": "Valais",
              "DE734": "Kassel, Landkreis", "DE261": "Aschaffenburg, Kreisfreie Stadt",
              "DE223": "Straubing, Kreisfreie Stadt", "DE278": "Günzburg", "AT311": "Innviertel",
              "UKN02": "Outer Belfast", "FR107": "Val-de-Marne", "IE023": "Mid-West", "ITH36": "Padova",
              "RO212": "Botosani", "NL341": "Zeeuwsch-Vlaanderen", "FR721": "Allier", "UKK15": "Wiltshire CC",
              "DE91A": "Peine", "NO041": "Aust-Agder", "RO322": "Ilfov", "PT111": "Alto Minho",
              "UKG22": "Shropshire CC", "AT211": "Klagenfurt-Villach", "FR722": "Cantal",
              "UKM35": "Inverclyde, East Renfrewshire and Renfrewshire", "DE11D": "Ostalbkreis", "DEF09": "Pinneberg",
              "DEG0J": "Saale-Holzland-Kreis", "FR812": "Gard", "RO411": "Dolj", "DE132": "Breisgau-Hochschwarzwald",
              "ES616": "Jaén", "TR423": "Düzce", "FR106": "Seine-Saint-Denis", "ITC46": "Bergamo", "BG421": "Plovdiv",
              "DE266": "Rhön-Grabfeld", "ITH31": "Verona", "LI000": "Liechtenstein", "ITI1A": "Grosseto",
              "ITI16": "Livorno", "RO226": "Vrancea", "FR532": "Charente-Maritime", "DE146": "Biberach",
              "AT112": "Nordburgenland", "SK032": "Banskobystrický kraj", "FR223": "Somme",
              "PL129": "Warszawski wschodni", "DEA58": "Märkischer Kreis", "DE40H": "Teltow-Fläming",
              "DE124": "Rastatt", "CZ052": "Královéhradecký kraj", "PL22C": "Tyski", "DE111": "Stuttgart, Stadtkreis",
              "IE013": "West", "UKK30": "Cornwall and Isles of Scilly",
              "BE335": "Arr. Verviers - communes francophones", "DE929": "Region Hannover", "DE21C": "Fürstenfeldbruck",
              "UKK14": "Swindon", "ITI42": "Rieti", "AT127": "Wiener Umland/Südteil", "UKF14": "Nottingham",
              "BG325": "Silistra", "DE234": "Amberg-Sulzbach", "HU331": "Bács-Kiskun", "ITF12": "Teramo",
              "RO121": "Alba", "UKM33": "East Ayrshire and North Ayrshire mainland", "DE257": "Erlangen-Höchstadt",
              "DE141": "Reutlingen", "DEA36": "Recklinghausen", "TR822": "Çankiri", "DE21B": "Freising",
              "DE91B": "Wolfenbüttel", "DE21J": "Pfaffenhofen an der Ilm", "BG423": "Pazardzhik", "ITF14": "Chieti",
              "DEA24": "Leverkusen, Kreisfreie Stadt", "SK022": "Trenciansky kraj", "FI1C1": "Varsinais-Suomi",
              "ES415": "Salamanca", "LT006": "Siauliu apskritis", "NL321": "Kop van Noord-Holland",
              "BE252": "Arr. Diksmuide", "BG343": "Yambol", "DEG02": "Gera, Kreisfreie Stadt", "ES241": "Huesca",
              "DE913": "Wolfsburg, Kreisfreie Stadt", "EL421": "Kalymnos, Karpathos, Kos, Rodos", "DE269": "Miltenberg",
              "HR04A": "Brodsko-posavska zupanija", "ITG2B": "Medio Campidano", "FR301": "Nord (FR)",
              "CH032": "Basel-Landschaft", "ITF35": "Salerno", "DE71D": "Rheingau-Taunus-Kreis", "FR513": "Mayenne",
              "CZ053": "Pardubický kraj", "DE407": "Elbe-Elster", "DE128": "Rhein-Neckar-Kreis",
              "DE125": "Heidelberg, Stadtkreis", "UKE44": "Calderdale and Kirklees",
              "UKM27": "Perth & Kinross and Stirling", "BE310": "Arr. Nivelles", "DE71A": "Main-Taunus-Kreis",
              "FR515": "Vendée", "FR253": "Orne", "ITC44": "Sondrio", "BG322": "Gabrovo", "PL517": "Walbrzyski",
              "ITG27": "Cagliari", "RO223": "Constanta", "TR633": "Osmaniye", "DEB3G": "Kusel", "CH021": "Bern",
              "ITG14": "Agrigento", "ES425": "Toledo", "FI1D6": "Pohjois-Pohjanmaa", "ES531": "Eivissa, Formentera",
              "PL324": "Przemyski", "DE224": "Deggendorf", "DE137": "Tuttlingen", "PL622": "Olsztynski",
              "TR905": "Artvin", "PL516": "Legnicko-Glogowski", "DED44": "Vogtlandkreis",
              "DE401": "Brandenburg an der Havel, Kreisfreie Stadt", "CH052": "Schaffhausen", "BG313": "Vratsa",
              "DE231": "Amberg, Kreisfreie Stadt", "EE004": "Lääne-Eesti", "DE23A": "Tirschenreuth", "TRA21": "Agri",
              "DE25B": "Roth", "BG414": "Pernik", "NL412": "Midden-Noord-Brabant", "MK007": "Severoistocen",
              "DE142": "Tübingen, Landkreis", "UKG31": "Birmingham", "NO021": "Hedmark", "PL344": "Lomzynski",
              "FR712": "Ardèche", "DEA2B": "Rheinisch-Bergischer Kreis", "PT184": "Baixo Alentejo", "HU101": "Budapest",
              "DE215": "Berchtesgadener Land", "FI1D1": "Etelä-Savo", "DE123": "Karlsruhe, Landkreis",
              "ES300": "Madrid", "DEA26": "Düren", "ITC15": "Novara", "DEA11": "Düsseldorf, Kreisfreie Stadt",
              "DE21E": "Landsberg am Lech", "FR434": "Territoire de Belfort", "DE94C": "Leer", "DEA5C": "Unna",
              "DE937": "Rotenburg (Wümme)", "DEB3K": "Südwestpfalz", "ES130": "Cantabria", "DEA44": "Höxter",
              "HU221": "Gyor-Moson-Sopron", "UKK42": "Torbay", "UKL17": "Bridgend and Neath Port Talbot",
              "BG333": "Shumen", "UKK21": "Bournemouth and Poole", "UKN03": "East of Northern Ireland (UK)",
              "FR718": "Haute-Savoie", "AT335": "Tiroler Unterland", "ITG26": "Nuoro", "HU102": "Pest",
              "NO061": "Sør-Trøndelag", "FR222": "Oise", "NL224": "Zuidwest-Gelderland", "UKM32": "Dumfries & Galloway",
              "ES612": "Cádiz", "DE21F": "Miesbach", "NL121": "Noord-Friesland", "AT332": "Innsbruck",
              "ES617": "Málaga", "ITH33": "Belluno", "DEE02": "Halle (Saale), Kreisfreie Stadt", "DEF0E": "Steinburg",
              "TR823": "Sinop", "ES640": "Melilla (ES)", "DEG0P": "Wartburgkreis", "DEB19": "Rhein-Hunsrück-Kreis",
              "TR813": "Bartin", "BE236": "Arr. Sint-Niklaas", "FR414": "Vosges", "DE217": "Dachau", "RO225": "Tulcea",
              "DE267": "Haßberge", "BG311": "Vidin", "FR622": "Aveyron", "RO124": "Harghita", "CH063": "Schwyz",
              "DE251": "Ansbach, Kreisfreie Stadt", "DE733": "Hersfeld-Rotenburg", "FR413": "Moselle",
              "DE148": "Ravensburg", "RO211": "Bacau", "FR714": "Isère", "SE321": "Västernorrlands län",
              "UKH21": "Luton", "UKL22": "Cardiff and Vale of Glamorgan", "DE40A": "Oberhavel", "AT331": "Außerfern",
              "DEA33": "Münster, Kreisfreie Stadt", "AT225": "West- und Südsteiermark", "AT212": "Oberkärnten",
              "DE119": "Hohenlohekreis", "BE324": "Arr. Mouscron", "ES424": "Guadalajara", "PT150": "Algarve",
              "CH025": "Jura", "NO071": "Nordland", "ITC33": "Genova", "FR214": "Haute-Marne",
              "DE26B": "Schweinfurt, Landkreis", "LT007": "Taurages apskritis", "BG315": "Lovech",
              "DEG01": "Erfurt, Kreisfreie Stadt", "BG331": "Varna", "DED2C": "Bautzen", "ES521": "Alicante / Alacant",
              "DK041": "Vestjylland", "ITF65": "Reggio di Calabria", "SE332": "Norrbottens län", "TRC33": "Sirnak",
              "DE405": "Barnim", "DEA47": "Paderborn", "FR814": "Lozère", "UKJ31": "Portsmouth", "NL213": "Twente",
              "CH051": "Glarus", "TRB24": "Hakkari", "DE11A": "Schwäbisch Hall", "RO313": "Dâmbovita",
              "DEB12": "Ahrweiler", "FR523": "Ille-et-Vilaine", "FI195": "Pohjanmaa", "TR422": "Sakarya",
              "UKJ34": "Isle of Wight", "NL113": "Overig Groningen", "HR044": "Varazdinska zupanija",
              "DEC04": "Saarlouis", "TR221": "Balikesir", "DE94B": "Grafschaft Bentheim", "DEF05": "Dithmarschen",
              "DE246": "Bayreuth, Landkreis", "ITG13": "Messina", "FR625": "Lot",
              "DE944": "Osnabrück, Kreisfreie Stadt", "FR813": "Hérault", "ITC47": "Brescia",
              "DEF0B": "Rendsburg-Eckernförde", "ITG2C": "Carbonia-Iglesias", "DE24C": "Lichtenfels",
              "FR533": "Deux-Sèvres", "NO022": "Oppland", "BE255": "Arr. Oostende", "FR514": "Sarthe",
              "DE26C": "Würzburg, Landkreis", "DE713": "Offenbach am Main, Kreisfreie Stadt",
              "DE721": "Gießen, Landkreis", "NO031": "Østfold", "BG312": "Montana", "CZ064": "Jihomoravský kraj",
              "DE118": "Heilbronn, Landkreis", "ITF47": "Bari", "CZ032": "Plzenský kraj", "RO412": "Gorj",
              "NO011": "Oslo", "HU233": "Tolna", "DEG0G": "Weimarer Land", "CZ063": "Kraj Vysocina",
              "BE212": "Arr. Mechelen", "PL227": "Rybnicki", "FR521": "Côtes-d'Armor",
              "DEB11": "Koblenz, Kreisfreie Stadt", "DE725": "Vogelsbergkreis", "RO221": "Braila",
              "HR036": "Istarska zupanija", "RO122": "Brasov", "EE006": "Kesk-Eesti", "CH031": "Basel-Stadt",
              "DE408": "Havelland", "FR522": "Finistère", "DE22B": "Straubing-Bogen", "BE258": "Arr. Veurne",
              "TR612": "Isparta", "DEF04": "Neumünster, Kreisfreie Stadt", "RO422": "Caras-Severin",
              "ITG19": "Siracusa", "DE715": "Bergstraße", "TR424": "Bolu", "ITH52": "Parma",
              "UKG11": "Herefordshire, County of", "DEB39": "Worms, Kreisfreie Stadt", "UKL12": "Gwynedd",
              "FR232": "Seine-Maritime", "NL414": "Zuidoost-Noord-Brabant", "FR103": "Yvelines", "DE938": "Heidekreis",
              "FR211": "Ardennes", "DEF07": "Nordfriesland", "DEC05": "Saarpfalz-Kreis", "RO316": "Prahova",
              "DEB13": "Altenkirchen (Westerwald)", "NL332": "Agglomeratie 's-Gravenhage", "ES242": "Teruel",
              "PL633": "Trojmiejski", "DEA53": "Hagen, Kreisfreie Stadt", "DE241": "Bamberg, Kreisfreie Stadt",
              "LV008": "Vidzeme", "DE915": "Göttingen", "ITI14": "Firenze",
              "UKK12": "Bath and North East Somerset, North Somerset and South Gloucestershire",
              "NL132": "Zuidoost-Drenthe", "UKH11": "Peterborough", "ES411": "Ávila", "PL213": "Miasto Kraków",
              "FR724": "Puy-de-Dôme", "DE26A": "Main-Spessart", "LV007": "Pieriga", "SE322": "Jämtlands län",
              "FR302": "Pas-de-Calais", "UKJ11": "Berkshire",
              "EL422": "Andros, Thira, Kea, Milos, Mykonos, Naxos, Paros, Syros, Tinos", "DE258": "Fürth, Landkreis",
              "BE351": "Arr. Dinant", "DE21D": "Garmisch-Partenkirchen", "ITG29": "Olbia-Tempio", "RO111": "Bihor",
              "PL225": "Bielski", "TRA12": "Erzincan", "ME000": "Crna Gora", "DE216": "Bad Tölz-Wolfratshausen",
              "PL621": "Elblaski", "UKF22": "Leicestershire CC and Rutland", "UKM50": "Aberdeen City and Aberdeenshire",
              "UKM36": "North Lanarkshire", "DE219": "Eichstätt", "ES533": "Menorca", "DE724": "Marburg-Biedenkopf",
              "HR04D": "Karlovacka zupanija", "DEA1A": "Wuppertal, Kreisfreie Stadt", "ITC31": "Imperia",
              "DEB14": "Bad Kreuznach", "EL413": "Chios", "DEA38": "Warendorf", "CZ071": "Olomoucký kraj",
              "DEB34": "Ludwigshafen am Rhein, Kreisfreie Stadt", "UKC13": "Darlington", "TR100": "Istanbul",
              "DE268": "Kitzingen", "ITF51": "Potenza", "DEF0C": "Schleswig-Flensburg", "DE24A": "Kronach",
              "ITC48": "Pavia", "NL327": "Het Gooi en Vechtstreek", "SE110": "Stockholms län",
              "AT111": "Mittelburgenland", "PL22B": "Sosnowiecki", "FR221": "Aisne", "DEB3J": "Mainz-Bingen",
              "UKM28": "West Lothian", "DE237": "Neustadt an der Waldnaab", "FR624": "Gers", "DEE08": "Burgenland (DE)",
              "CH056": "Graubünden", "ITH34": "Treviso", "ES220": "Navarra", "TR722": "Sivas",
              "DE242": "Bayreuth, Kreisfreie Stadt",
              "UKM31": "East Dunbartonshire, West Dunbartonshire and Helensburgh & Lomond", "CH024": "Neuchâtel",
              "DE248": "Forchheim", "TRB23": "Bitlis", "BG323": "Ruse", "CH055": "St. Gallen", "PL229": "Gliwicki",
              "ES611": "Almería", "BG334": "Targovishte", "ITF33": "Napoli", "UKF15": "North Nottinghamshire",
              "DE138": "Konstanz", "TRA11": "Erzurum", "FI194": "Etelä-Pohjanmaa", "ITC32": "Savona",
              "NO032": "Buskerud", "TRA22": "Kars", "RO414": "Olt", "DE245": "Bamberg, Landkreis", "FR524": "Morbihan",
              "BG425": "Kardzhali", "RO317": "Teleorman", "DE716": "Darmstadt-Dieburg", "ITH10": "Bolzano-Bozen",
              "AT130": "Wien", "UKE12": "East Riding of Yorkshire", "TR832": "Tokat", "CZ051": "Liberecký kraj",
              "HR04B": "Osjecko-baranjska zupanija", "DE135": "Rottweil", "ITC12": "Vercelli", "DED52": "Leipzig",
              "NL133": "Zuidwest-Drenthe", "DEA45": "Lippe", "TR621": "Adana",
              "UKN05": "West and South of Northern Ireland (UK)", "IE011": "Border", "AT113": "Südburgenland",
              "UKE32": "Sheffield", "DEG0C": "Gotha", "ITI34": "Ascoli Piceno", "DEB37": "Pirmasens, Kreisfreie Stadt",
              "DEE03": "Magdeburg, Kreisfreie Stadt", "ITC16": "Cuneo", "ITH59": "Rimini",
              "UKL13": "Conwy and Denbighshire", "DE13A": "Waldshut", "TR611": "Antalya", "MK005": "Pelagoniski",
              "FI1C3": "Päijät-Häme", "LT003": "Klaipedos apskritis", "FR105": "Hauts-de-Seine",
              "DEA19": "Solingen, Kreisfreie Stadt", "FI1C2": "Kanta-Häme", "DE936": "Osterholz",
              "UKD62": "Cheshire East", "DE935": "Lüneburg, Landkreis",
              "UKM62": "Inverness & Nairn and Moray, Badenoch & Strathspey",
              "DE233": "Weiden in der Oberpfalz, Kreisfreie Stadt", "ES532": "Mallorca",
              "BE241": "Arr. Halle-Vilvoorde", "PL311": "Bialski", "FR628": "Tarn-et-Garonne",
              "DE238": "Regensburg, Landkreis", "TR833": "Çorum", "BE256": "Arr. Roeselare", "DE71B": "Odenwaldkreis",
              "EL411": "Lesvos, Limnos", "ES703": "El Hierro", "DE149": "Sigmaringen", "ITG11": "Trapani",
              "LT009": "Utenos apskritis", "TR613": "Burdur", "ITC4D": "Monza e della Brianza",
              "DE804": "Schwerin, Kreisfreie Stadt", "TRB14": "Tunceli", "FR412": "Meuse", "DE926": "Holzminden",
              "DE911": "Braunschweig, Kreisfreie Stadt", "TR332": "Afyonkarahisar", "DE40D": "Ostprignitz-Ruppin",
              "FR101": "Paris", "DED43": "Mittelsachsen", "FR711": "Ain", "TR333": "Kütahya", "BE323": "Arr. Mons",
              "PL514": "Miasto Wroclaw", "DE917": "Helmstedt", "LT002": "Kauno apskritis", "ITF44": "Brindisi",
              "DE94F": "Vechta", "TR322": "Denizli", "BE234": "Arr. Gent",
              "UKM63": "Lochaber, Skye & Lochalsh, Arran & Cumbrae and Argyll & Bute", "HU213": "Veszprém",
              "DEE0A": "Mansfeld-Südharz", "AT334": "Tiroler Oberland", "UKK22": "Dorset CC", "IE012": "Midland",
              "DE732": "Fulda", "TR421": "Kocaeli", "DEA1B": "Kleve", "DEB3F": "Kaiserslautern, Landkreis",
              "DE272": "Kaufbeuren, Kreisfreie Stadt", "CH040": "Zürich", "RO315": "Ialomita", "TR714": "Nevsehir",
              "ITH32": "Vicenza", "NL326": "Groot-Amsterdam", "UKG23": "Stoke-on-Trent", "ES111": "A Coruña",
              "BE254": "Arr. Kortrijk", "DEF08": "Ostholstein", "PL127": "Miasto Warszawa", "ITI31": "Pesaro e Urbino",
              "UKE41": "Bradford", "HR042": "Zagrebacka zupanija", "SE214": "Gotlands län",
              "AT122": "Niederösterreich-Süd", "DEG0D": "Sömmerda", "DE722": "Lahn-Dill-Kreis", "ITF62": "Crotone",
              "UKK43": "Devon CC", "DED45": "Zwickau", "DE40I": "Uckermark", "UKJ21": "Brighton and Hove",
              "DE256": "Ansbach, Landkreis", "TRC31": "Mardin", "BE342": "Arr. Bastogne", "PL345": "Suwalski",
              "ITI12": "Lucca", "DE236": "Neumarkt in der Oberpfalz", "ITI45": "Frosinone",
              "DE409": "Märkisch-Oderland", "CZ031": "Jihocecký kraj",
              "DEB36": "Neustadt an der Weinstraße, Kreisfreie Stadt", "DE947": "Aurich",
              "DEB3H": "Südliche Weinstraße", "FR627": "Tarn", "IE025": "South-West (IE)", "DE24B": "Kulmbach",
              "DE116": "Rems-Murr-Kreis", "ES211": "Araba/Álava", "DEA41": "Bielefeld, Kreisfreie Stadt",
              "DE21G": "Mühldorf am Inn", "ITC41": "Varese", "ITC11": "Torino", "DEA37": "Steinfurt",
              "DE502": "Bremerhaven, Kreisfreie Stadt", "FR822": "Hautes-Alpes", "UKL18": "Swansea",
              "DEG0F": "Ilm-Kreis", "DE275": "Aichach-Friedberg", "BE341": "Arr. Arlon", "ES412": "Burgos",
              "NL325": "Zaanstreek", "DEB3A": "Zweibrücken, Kreisfreie Stadt", "TR212": "Edirne",
              "DEF02": "Kiel, Kreisfreie Stadt", "DEB3I": "Rhein-Pfalz-Kreis", "DED42": "Erzgebirgskreis",
              "DE945": "Wilhelmshaven, Kreisfreie Stadt", "RO112": "Bistrita-Nasaud", "SE213": "Kalmar län",
              "DEB35": "Mainz, Kreisfreie Stadt", "UKM38": "South Lanarkshire", "FR621": "Ariège",
              "DE934": "Lüchow-Dannenberg", "DE927": "Nienburg (Weser)", "DEA32": "Gelsenkirchen, Kreisfreie Stadt",
              "FR713": "Drôme", "PL431": "Gorzowski", "FR264": "Yonne", "FR615": "Pyrénées-Atlantiques",
              "RO224": "Galati", "DE803": "Rostock, Kreisfreie Stadt", "EL433": "Rethymni",
              "AT342": "Rheintal-Bodenseegebiet", "TR821": "Kastamonu", "DEB25": "Trier-Saarburg",
              "DEB23": "Eifelkreis Bitburg-Prüm", "DE93B": "Verden", "TR812": "Karabük",
              "DE94D": "Oldenburg, Landkreis", "DE27B": "Ostallgäu", "CH062": "Uri", "FR716": "Rhône",
              "DEB3C": "Bad Dürkheim", "DE94H": "Wittmund", "ES413": "León", "NO072": "Troms", "EE001": "Põhja-Eesti",
              "DEF0D": "Segeberg", "FI1D5": "Keski-Pohjanmaa", "ITI11": "Massa-Carrara", "ITG15": "Caltanissetta",
              "FR626": "Hautes-Pyrénées", "RO424": "Timis", "ES421": "Albacete", "ES613": "Córdoba",
              "ITF32": "Benevento", "TRA13": "Bayburt", "NL212": "Zuidwest-Overijssel", "DE115": "Ludwigsburg",
              "SE211": "Jönköpings län", "DE501": "Bremen, Kreisfreie Stadt", "HU323": "Szabolcs-Szatmár-Bereg",
              "ITG16": "Enna", "ES523": "Valencia / València", "ITC13": "Biella", "NL338": "Oost-Zuid-Holland",
              "DEG0L": "Greiz", "ES630": "Ceuta (ES)", "ITF13": "Pescara", "RO314": "Giurgiu", "ES414": "Palencia",
              "DEC03": "Neunkirchen", "UKF11": "Derby", "NL422": "Midden-Limburg", "BE321": "Arr. Ath",
              "BG413": "Blagoevgrad", "DE259": "Nürnberger Land", "NL230": "Flevoland", "TR211": "Tekirdag",
              "TRB13": "Bingöl", "UKJ12": "Milton Keynes", "UKD41": "Blackburn with Darwen", "DE922": "Diepholz",
              "BE231": "Arr. Aalst", "ITH53": "Reggio nell'Emilia", "IE024": "South-East (IE)",
              "CZ010": "Hlavní mesto Praha", "PL424": "Miasto Szczecin", "DEG0I": "Saalfeld-Rudolstadt",
              "HR034": "Sibensko-kninska zupanija", "DE139": "Lörrach", "NL122": "Zuidwest-Friesland",
              "DEB24": "Vulkaneifel", "UKF12": "East Derbyshire", "DE244": "Hof, Kreisfreie Stadt", "HU332": "Békés",
              "FI197": "Pirkanmaa", "NL211": "Noord-Overijssel", "BE325": "Arr. Soignies", "FR422": "Haut-Rhin",
              "UKE13": "North and North East Lincolnshire", "DK031": "Fyn", "DE719": "Main-Kinzig-Kreis",
              "DE112": "Böblingen", "UKL15": "Central Valleys", "TR522": "Karaman", "ES704": "Fuerteventura",
              "ES213": "Bizkaia", "DEA15": "Mönchengladbach, Kreisfreie Stadt", "DE239": "Schwandorf",
              "DEB31": "Frankenthal (Pfalz), Kreisfreie Stadt", "PL332": "Sandomiersko-jedrzejowski", "UKD74": "Wirral",
              "ES432": "Cáceres", "ITH35": "Venezia", "DEA42": "Gütersloh", "DE40G": "Spree-Neiße",
              "DED41": "Chemnitz, Kreisfreie Stadt", "PT185": "Lezíria do Tejo", "ITC4A": "Cremona",
              "PL312": "Chelmsko-zamojski", "RO213": "Iasi", "PL217": "Tarnowski", "DEA23": "Köln, Kreisfreie Stadt",
              "HR04E": "Sisacko-moslavacka zupanija", "DEA14": "Krefeld, Kreisfreie Stadt", "ITI43": "Roma",
              "HR035": "Splitsko-dalmatinska zupanija", "FI1C4": "Kymenlaakso", "PL331": "Kielecki", "UKJ41": "Medway",
              "DEB15": "Birkenfeld", "ES422": "Ciudad Real", "DE736": "Waldeck-Frankenberg",
              "HU212": "Komárom-Esztergom", "UKD63": "Cheshire West and Chester", "BG314": "Pleven",
              "UKE45": "Wakefield", "ITG28": "Oristano", "FR212": "Aube", "DEB16": "Cochem-Zell",
              "NL423": "Zuid-Limburg", "FR431": "Doubs", "UKC12": "South Teesside", "TRB11": "Malatya",
              "AT126": "Wiener Umland/Nordteil", "DEB3E": "Germersheim", "FR511": "Loire-Atlantique",
              "ITH57": "Ravenna", "TR510": "Ankara", "PL12A": "Warszawski zachodni", "TR331": "Manisa", "ES112": "Lugo",
              "MK006": "Poloski", "UKK23": "Somerset", "UKF16": "South Nottinghamshire", "FI1D2": "Pohjois-Savo",
              "UKE22": "North Yorkshire CC", "CH022": "Freiburg", "DK050": "Nordjylland", "UKL11": "Isle of Anglesey",
              "CZ041": "Karlovarský kraj", "TR632": "Kahramanmaras", "PL114": "Lódzki",
              "DEA55": "Herne, Kreisfreie Stadt", "ES614": "Granada", "PL314": "Lubelski", "UKD71": "East Merseyside",
              "UKM24": "Scottish Borders", "DE300": "Berlin", "UKK41": "Plymouth",
              "HR045": "Koprivnicko-krizevacka zupanija", "FR231": "Eure", "TR834": "Amasya",
              "DE273": "Kempten (Allgäu), Kreisfreie Stadt", "PT200": "Região Autónoma dos Açores (PT)",
              "DE212": "München, Kreisfreie Stadt", "UKL23": "Flintshire and Wrexham", "DE735": "Schwalm-Eder-Kreis",
              "RO114": "Maramures", "SE122": "Södermanlands län", "UKH31": "Southend-on-Sea",
              "NL226": "Arnhem/Nijmegen", "UKF13": "South and West Derbyshire", "DE227": "Landshut, Landkreis",
              "DEC01": "Regionalverband Saarbrücken", "BE344": "Arr. Neufchâteau", "DEB1A": "Rhein-Lahn-Kreis",
              "UKD11": "West Cumbria", "BG332": "Dobrich", "DE274": "Memmingen, Kreisfreie Stadt",
              "DK032": "Sydjylland", "DEA1D": "Rhein-Kreis Neuss", "ITF48": "Barletta-Andria-Trani",
              "DE404": "Potsdam, Kreisfreie Stadt", "FR102": "Seine-et-Marne", "HR032": "Licko-senjska zupanija",
              "UKF24": "West Northamptonshire", "UKL16": "Gwent Valleys", "DE942": "Emden, Kreisfreie Stadt",
              "NO062": "Nord-Trøndelag", "SE232": "Västra Götalands län", "DEA31": "Bottrop, Kreisfreie Stadt",
              "BE334": "Arr. Waremme", "UKG36": "Dudley", "TRC21": "Sanliurfa", "DEC02": "Merzig-Wadern",
              "EL412": "Ikaria, Samos", "UKG32": "Solihull", "PL415": "Miasto Poznan", "AT213": "Unterkärnten",
              "DK022": "Vest- og Sydsjælland", "BE235": "Arr. Oudenaarde", "AT313": "Mühlviertel", "RO423": "Hunedoara",
              "UKJ32": "Southampton", "RO413": "Mehedinti", "ES615": "Huelva", "DE136": "Schwarzwald-Baar-Kreis",
              "NO042": "Vest-Agder", "DE406": "Dahme-Spreewald", "DE255": "Schwabach, Kreisfreie Stadt",
              "PL113": "Miasto Lódz", "DEA29": "Heinsberg", "PL128": "Radomski", "ITI44": "Latina",
              "DE253": "Fürth, Kreisfreie Stadt", "HR041": "Grad Zagreb", "AT312": "Linz-Wels", "BG324": "Razgrad",
              "DE147": "Bodenseekreis", "DE71C": "Offenbach, Landkreis", "AT121": "Mostviertel-Eisenwurzen",
              "ITI13": "Pistoia", "UKG38": "Walsall", "BE232": "Arr. Dendermonde", "PL515": "Jeleniogórski",
              "ITC20": "Valle d'Aosta/Vallée d'Aoste", "DED21": "Dresden, Kreisfreie Stadt",
              "HU311": "Borsod-Abaúj-Zemplén", "DE22C": "Dingolfing-Landau", "TRA23": "Igdir", "FI1C5": "Etelä-Karjala",
              "UKM37": "South Ayrshire", "DE40C": "Oder-Spree", "ES706": "La Gomera", "DE21I": "Neuburg-Schrobenhausen",
              "HR031": "Primorsko-goranska zupanija", "ITF34": "Avellino", "RO215": "Suceava",
              "DE21K": "Rosenheim, Landkreis", "SE125": "Västmanlands län", "DEB38": "Speyer, Kreisfreie Stadt",
              "FR715": "Loire", "DE923": "Hameln-Pyrmont", "DEF0F": "Stormarn", "HU322": "Jász-Nagykun-Szolnok",
              "DEE0D": "Stendal", "DE113": "Esslingen", "MK004": "Jugoistocen", "DE27D": "Donau-Ries",
              "CY000": "Kypros", "NL324": "Agglomeratie Haarlem", "DE925": "Hildesheim", "SK010": "Bratislavský kraj",
              "TR425": "Yalova", "UKM34": "Glasgow City", "FR241": "Cher", "UKN04": "North of Northern Ireland (UK)",
              "BE345": "Arr. Virton", "DEA1C": "Mettmann", "DEF0A": "Plön", "UKD42": "Blackpool", "DEA1F": "Wesel",
              "ITC43": "Lecco", "PL518": "Wroclawski", "FR421": "Bas-Rhin", "RO421": "Arad", "IE021": "Dublin",
              "PL325": "Rzeszowski", "UKD73": "Sefton", "AT226": "Westliche Obersteiermark", "FR832": "Haute-Corse",
              "BE223": "Arr. Tongeren", "AT124": "Waldviertel", "DE932": "Cuxhaven", "BE211": "Arr. Antwerpen",
              "BG422": "Haskovo", "ITH54": "Modena", "TRC34": "Siirt", "NL322": "Alkmaar en omgeving",
              "DEB3D": "Donnersbergkreis", "DED2D": "Görlitz", "FR612": "Gironde", "DE145": "Alb-Donau-Kreis",
              "SE231": "Hallands län", "BE253": "Arr. Ieper", "FR811": "Aude", "DEG09": "Unstrut-Hainich-Kreis",
              "LT004": "Marijampoles apskritis", "DE25C": "Weißenburg-Gunzenhausen", "BG321": "Veliko Tarnovo",
              "NO051": "Hordaland", "CZ042": "Ústecký kraj", "SE121": "Uppsala län", "ITH58": "Forlì-Cesena",
              "DEG0N": "Eisenach, Kreisfreie Stadt", "ITH42": "Udine", "UKE21": "York", "TR831": "Samsun",
              "BG344": "Stara Zagora", "DE712": "Frankfurt am Main, Kreisfreie Stadt", "CH013": "Genève",
              "TR906": "Gümüshane", "DE228": "Passau, Landkreis", "BE327": "Arr. Tournai", "IS002": "Landsbyggd",
              "DE218": "Ebersberg", "TR411": "Bursa", "DE12C": "Freudenstadt", "ITF31": "Caserta",
              "DE21M": "Traunstein", "TR213": "Kirklareli", "FR623": "Haute-Garonne", "DEE0C": "Salzlandkreis",
              "DE276": "Augsburg, Landkreis", "ITI18": "Arezzo", "DE232": "Regensburg, Kreisfreie Stadt",
              "DE249": "Hof, Landkreis", "ITF61": "Cosenza", "DE27C": "Unterallgäu", "ITC42": "Como",
              "DE943": "Oldenburg (Oldenburg), Kreisfreie Stadt", "DE126": "Mannheim, Stadtkreis",
              "UKK13": "Gloucestershire", "UKD72": "Liverpool", "PL343": "Bialostocki",
              "DEE04": "Altmarkkreis Salzwedel", "DE916": "Goslar", "DE737": "Werra-Meißner-Kreis",
              "MK001": "Vardarski", "DE225": "Freyung-Grafenau", "FR411": "Meurthe-et-Moselle", "FR531": "Charente",
              "DE912": "Salzgitter, Kreisfreie Stadt", "PL432": "Zielonogórski", "DEA5A": "Siegen-Wittgenstein",
              "DE403": "Frankfurt (Oder), Kreisfreie Stadt", "DEB18": "Neuwied", "LV003": "Kurzeme",
              "DE262": "Schweinfurt, Kreisfreie Stadt", "DK042": "Østjylland", "HU223": "Zala",
              "UKM66": "Shetland Islands", "DE252": "Erlangen, Kreisfreie Stadt", "IE022": "Mid-East",
              "BG411": "Sofia (stolitsa)", "LT00A": "Vilniaus apskritis", "CH054": "Appenzell Innerrhoden",
              "BE343": "Arr. Marche-en-Famenne", "LU000": "Luxembourg", "ES514": "Tarragona", "UKC23": "Sunderland",
              "TR222": "Çanakkale", "ITH51": "Piacenza", "DE600": "Hamburg", "ITI17": "Pisa", "BG424": "Smolyan",
              "HR033": "Zadarska zupanija", "UKD12": "East Cumbria", "HR047": "Bjelovarsko-bilogorska zupanija",
              "ES418": "Valladolid", "PL634": "Gdanski", "NO053": "Møre og Romsdal", "DE21L": "Starnberg",
              "DE402": "Cottbus, Kreisfreie Stadt", "UKJ14": "Oxfordshire", "PL418": "Poznanski", "TR902": "Ordu",
              "DEB33": "Landau in der Pfalz, Kreisfreie Stadt", "UKG33": "Coventry", "DEG0B": "Schmalkalden-Meiningen",
              "DE211": "Ingolstadt, Kreisfreie Stadt", "DE914": "Gifhorn", "NL112": "Delfzijl en omgeving",
              "PL323": "Krosnienski", "NL323": "IJmond", "ITC4B": "Mantova", "IS001": "Höfudborgarsvædi",
              "DED2F": "Sächsische Schweiz-Osterzgebirge", "ES243": "Zaragoza", "ES511": "Barcelona",
              "UKE11": "Kingston upon Hull, City of", "DE928": "Schaumburg", "RO312": "Calarasi",
              "UKG12": "Worcestershire", "ES513": "Lleida", "DE731": "Kassel, Kreisfreie Stadt", "AT221": "Graz",
              "DEE05": "Anhalt-Bitterfeld", "ES114": "Pontevedra", "UKM65": "Orkney Islands", "DEE0B": "Saalekreis",
              "PL416": "Kaliski", "UKM64": "Eilean Siar (Western Isles)", "FR108": "Val-d'Oise", "BE242": "Arr. Leuven",
              "FI1D4": "Kainuu", "ES707": "La Palma", "PL623": "Elcki", "FR717": "Savoie", "UKM26": "Falkirk",
              "UKF25": "North Northamptonshire", "PL116": "Sieradzki", "HU321": "Hajdú-Bihar",
              "FR263": "Saône-et-Loire", "HR048": "Viroviticko-podravska zupanija", "DED53": "Nordsachsen",
              "UKE42": "Leeds", "HR037": "Dubrovacko-neretvanska zupanija", "ITC34": "La Spezia",
              "DE711": "Darmstadt, Kreisfreie Stadt", "SE212": "Kronobergs län", "UKL21": "Monmouthshire and Newport",
              "DEB1B": "Westerwaldkreis", "TR901": "Trabzon", "ES423": "Cuenca",
              "UKC11": "Hartlepool and Stockton-on-Tees", "NL225": "Achterhoek", "AT314": "Steyr-Kirchdorf",
              "ES705": "Gran Canaria", "SE312": "Dalarnas län", "DEG03": "Jena, Kreisfreie Stadt",
              "DEC06": "St. Wendel", "DE117": "Heilbronn, Stadtkreis", "DEA34": "Borken", "BE332": "Arr. Liège",
              "FI1B1": "Helsinki-Uusimaa", "TRB12": "Elazig", "FR262": "Nièvre", "LV006": "Riga",
              "UKJ22": "East Sussex CC", "DE94G": "Wesermarsch", "FR244": "Indre-et-Loire", "NO033": "Vestfold",
              "DE21H": "München, Landkreis", "TRC22": "Diyarbakir", "DEB22": "Bernkastel-Wittlich",
              "HR043": "Krapinsko-zagorska zupanija", "DE94A": "Friesland (DE)", "DE254": "Nürnberg, Kreisfreie Stadt",
              "TR413": "Bilecik", "HU211": "Fejér", "DE279": "Neu-Ulm", "DED51": "Leipzig, Kreisfreie Stadt",
              "ITF52": "Matera", "FR631": "Corrèze", "RO216": "Vaslui", "FR823": "Alpes-Maritimes",
              "PL22A": "Katowicki", "SK023": "Nitriansky kraj", "DE40E": "Potsdam-Mittelmark", "FR246": "Loiret",
              "TR715": "Kirsehir", "NL123": "Zuidoost-Friesland", "ITF63": "Catanzaro", "SK021": "Trnavský kraj",
              "DEG0M": "Altenburger Land", "BE100": "Arr. de Bruxelles-Capitale / Arr. van Brussel-Hoofdstad",
              "ITC14": "Verbano-Cusio-Ossola", "FR824": "Bouches-du-Rhône", "ITF64": "Vibo Valentia",
              "DEA18": "Remscheid, Kreisfreie Stadt", "UKH32": "Thurrock", "FR611": "Dordogne", "DE40F": "Prignitz",
              "EL434": "Chania", "EE007": "Kirde-Eesti", "DE27A": "Lindau (Bodensee)", "CZ072": "Zlínský kraj",
              "DE114": "Göppingen", "DEA27": "Rhein-Erft-Kreis", "DEA59": "Olpe", "ITH37": "Rovigo", "MT001": "Malta",
              "DED2E": "Meißen", "CH057": "Thurgau", "CH011": "Vaud", "UKG24": "Staffordshire CC",
              "BE222": "Arr. Maaseik", "ES416": "Segovia", "NO012": "Akershus", "RO123": "Covasna", "DE933": "Harburg",
              "BE336": "Bezirk Verviers - Deutschsprachige Gemeinschaft", "FR826": "Vaucluse",
              "DE11B": "Main-Tauber-Kreis", "RO115": "Satu Mare", "DEG04": "Suhl, Kreisfreie Stadt", "ES431": "Badajoz",
              "UKM25": "Edinburgh, City of", "PL326": "Tarnobrzeski", "ES417": "Soria",
              "DE127": "Neckar-Odenwald-Kreis", "FI1D7": "Lappi", "EL432": "Lasithi", "CZ020": "Stredoceský kraj",
              "DK021": "Østsjælland", "AT315": "Traunviertel", "TR723": "Yozgat", "DEG0A": "Kyffhäuserkreis",
              "ITI19": "Siena", "ITG18": "Ragusa", "FI196": "Satakunta", "DE718": "Hochtaunuskreis",
              "DE263": "Würzburg, Kreisfreie Stadt", "ITH41": "Pordenone", "MK002": "Istocen", "ES419": "Zamora",
              "PT16B": "Oeste", "AT323": "Salzburg und Umgebung", "LV005": "Latgale", "LT001": "Alytaus apskritis",
              "HR046": "Medimurska zupanija", "UKG39": "Wolverhampton", "DE93A": "Uelzen", "PL315": "Pulawski",
              "CZ080": "Moravskoslezský kraj", "UKL24": "Powys", "TRB22": "Mus", "SK042": "Kosický kraj",
              "SK041": "Presovský kraj", "NL221": "Veluwe", "ES230": "La Rioja", "SK031": "Zilinský kraj",
              "BG412": "Sofia", "BE221": "Arr. Hasselt", "DEA2C": "Rhein-Sieg-Kreis", "RO126": "Sibiu",
              "DE717": "Groß-Gerau", "ITG25": "Sassari", "DE226": "Kelheim", "ITF11": "L'Aquila", "HU312": "Heves",
              "DE948": "Cloppenburg", "HR049": "Pozesko-slavonska zupanija", "TR811": "Zonguldak", "ITF43": "Taranto",
              "LT005": "Panevezio apskritis", "SE311": "Värmlands län", "BE353": "Arr. Philippeville",
              "DEB3B": "Alzey-Worms", "DE264": "Aschaffenburg, Landkreis", "UKN01": "Belfast",
              "DE129": "Pforzheim, Stadtkreis", "PL228": "Bytomski", "ITH55": "Bologna",
              "DE271": "Augsburg, Kreisfreie Stadt", "DEA56": "Ennepe-Ruhr-Kreis", "UKL14": "South West Wales",
              "BE322": "Arr. Charleroi", "DEG05": "Weimar, Kreisfreie Stadt", "ITG17": "Catania", "RO415": "Vâlcea",
              "ITH44": "Trieste", "FI200": "Åland", "DEA46": "Minden-Lübbecke", "FR104": "Essonne",
              "UKH25": "Central Bedfordshire", "DE21A": "Erding", "DE144": "Ulm, Stadtkreis", "ES113": "Ourense",
              "TR521": "Konya", "DE131": "Freiburg im Breisgau, Stadtkreis", "BE331": "Arr. Huy", "AT222": "Liezen",
              "DEA16": "Mülheim an der Ruhr, Kreisfreie Stadt", "ITH43": "Gorizia", "BE326": "Arr. Thuin",
              "UKE31": "Barnsley, Doncaster and Rotherham", "FR613": "Landes", "DE143": "Zollernalbkreis",
              "NL411": "West-Noord-Brabant", "UKF30": "Lincolnshire", "DK012": "Københavns omegn", "ITF21": "Isernia",
              "FR251": "Calvados", "HU231": "Baranya", "PL411": "Pilski", "DEF06": "Herzogtum Lauenburg",
              "ES522": "Castellón / Castelló", "HU313": "Nógrád", "UKG13": "Warwickshire",
              "DEB21": "Trier, Kreisfreie Stadt", "UKC21": "Northumberland", "FI193": "Keski-Suomi",
              "PL414": "Koninski", "DE918": "Northeim", "FR512": "Maine-et-Loire", "ITI21": "Perugia",
              "ES120": "Asturias", "TR711": "Kirikkale", "DE22A": "Rottal-Inn", "CH061": "Luzern", "HU232": "Somogy",
              "ITG2A": "Ogliastra", "DE247": "Coburg, Landkreis", "DEE01": "Dessau-Roßlau, Kreisfreie Stadt",
              "FR723": "Haute-Loire", "TR712": "Aksaray", "DE221": "Landshut, Kreisfreie Stadt", "FR243": "Indre",
              "RO125": "Mures", "HR04C": "Vukovarsko-srijemska zupanija", "CH023": "Solothurn",
              "SE123": "Östergötlands län", "UKH14": "Suffolk", "NL333": "Delft en Westland", "AT125": "Weinviertel",
              "SE313": "Gävleborgs län", "ES708": "Lanzarote", "FR821": "Alpes-de-Haute-Provence", "HU333": "Csongrád",
              "DEA35": "Coesfeld", "DEA51": "Bochum, Kreisfreie Stadt", "DE277": "Dillingen an der Donau",
              "DEE0E": "Wittenberg", "TRC12": "Adiyaman", "DEG06": "Eichsfeld", "PT181": "Alentejo Litoral",
              "NO034": "Telemark", "DE919": "Osterode am Harz", "UKJ13": "Buckinghamshire CC", "TR631": "Hatay",
              "UKF21": "Leicester", "LV009": "Zemgale", "ES212": "Gipuzkoa", "DEA2A": "Oberbergischer Kreis",
              "FR633": "Haute-Vienne", "TR622": "Mersin", "ITC4C": "Milano", "AT333": "Osttirol",
              "DE25A": "Neustadt an der Aisch-Bad Windsheim", "PL115": "Piotrkowski", "NL421": "Noord-Limburg",
              "FR432": "Jura", "TR323": "Mugla", "ITG12": "Palermo", "ITC18": "Alessandria", "CH033": "Aargau",
              "DE12B": "Enzkreis", "SE224": "Skåne län", "DEB17": "Mayen-Koblenz", "RO116": "Salaj",
              "DEG0E": "Hildburghausen", "RO214": "Neamt", "UKM21": "Angus and Dundee City", "ITF46": "Foggia",
              "DEA28": "Euskirchen", "DE12A": "Calw", "SE331": "Västerbottens län", "ITH20": "Trento", "DE939": "Stade",
              "DE214": "Altötting", "DEA43": "Herford", "DK013": "Nordsjælland", "DE235": "Cham",
              "UKM22": "Clackmannanshire and Fife", "TR310": "Izmir", "NL413": "Noordoost-Noord-Brabant",
              "DE71E": "Wetteraukreis", "TR903": "Giresun", "BE257": "Arr. Tielt", "UKH12": "Cambridgeshire CC",
              "NO043": "Rogaland", "LT008": "Telsiu apskritis", "DE121": "Baden-Baden, Stadtkreis",
              "NO052": "Sogn og Fjordane", "ES620": "Murcia", "DEA22": "Bonn, Kreisfreie Stadt",
              "MT002": "Gozo and Comino / Ghawdex u Kemmuna", "DE40B": "Oberspreewald-Lausitz", "ES709": "Tenerife",
              "DE11C": "Heidenheim", "ITC49": "Lodi", "DE243": "Coburg, Kreisfreie Stadt", "DEE06": "Jerichower Land",
              "NL131": "Noord-Drenthe", "AT223": "Östliche Obersteiermark", "BE251": "Arr. Brugge", "TRC32": "Batman",
              "ES512": "Girona", "DEA52": "Dortmund, Kreisfreie Stadt", "ITF22": "Campobasso",
              "UKK11": "Bristol, City of", "MK008": "Skopski", "UKM23": "East Lothian and Midlothian",
              "DEA17": "Oberhausen, Kreisfreie Stadt", "DE133": "Emmendingen", "FR614": "Lot-et-Garonne",
              "UKG37": "Sandwell", "BG415": "Kyustendil", "TR721": "Kayseri", "UKG21": "Telford and Wrekin",
              "BE233": "Arr. Eeklo", "BG341": "Burgas", "FR433": "Haute-Saône", "ITI35": "Fermo", "DK014": "Bornholm",
              "FR815": "Pyrénées-Orientales", "DE941": "Delmenhorst, Kreisfreie Stadt",
              "DE714": "Wiesbaden, Kreisfreie Stadt", "DEA5B": "Soest", "RO222": "Buzau", "FR632": "Creuse",
              "DEA13": "Essen, Kreisfreie Stadt", "NL339": "Groot-Rijnmond", "NO073": "Finnmark",
              "BE213": "Arr. Turnhout", "DEA2D": "Städteregion Aachen", "DE134": "Ortenaukreis",
              "DEF01": "Flensburg, Kreisfreie Stadt", "EE008": "Lõuna-Eesti", "TRA24": "Ardahan",
              "DK011": "Byen København", "DEG07": "Nordhausen", "NL111": "Oost-Groningen", "BG342": "Sliven",
              "SE124": "Örebro län", "ITI41": "Viterbo", "DE122": "Karlsruhe, Stadtkreis", "DEE07": "Börde",
              "DE94E": "Osnabrück, Landkreis", "TR713": "Nigde", "ITC17": "Asti",
              "DE213": "Rosenheim, Kreisfreie Stadt", "RO321": "Bucuresti", "ITI22": "Terni", "MK003": "Jugozapaden",
              "TR334": "Usak", "UKC14": "Durham CC", "UKM61": "Caithness & Sutherland and Ross & Cromarty",
              "AT341": "Bludenz-Bregenzer Wald", "FR534": "Vienne", "FR831": "Corse-du-Sud", "TR904": "Rize",
              "TRB21": "Van", "RO113": "Cluj", "FR252": "Manche", "RO311": "Arges", "AT322": "Pinzgau-Pongau",
              "AT123": "Sankt Pölten", "FR245": "Loir-et-Cher", "SE221": "Blekinge län", "FR825": "Var",
              "ITF45": "Lecce", "HU222": "Vas", "DE723": "Limburg-Weilburg", "FR242": "Eure-et-Loir", "ITI32": "Ancona",
              "DEG0K": "Saale-Orla-Kreis", "UKC22": "Tyneside", "DEE09": "Harz", "PL224": "Czestochowski",
              "DE229": "Regen", "TRC13": "Kilis", "PL117": "Skierniewicki", "CH065": "Nidwalden", "NL310": "Utrecht",
              "BE352": "Arr. Namur", "DE931": "Celle", "ITI15": "Prato", "DEB32": "Kaiserslautern, Kreisfreie Stadt"}
